version: '3.6'
services:
 tomcatserver:
   image: srikanthtekula/apache-tomcat-8.2.0:v1
   container_name: ApacheTomcatServer
   ports:
   -  9090:9090
   volumes:
   -  tomcat-data:/usr/local/tomcat/
   -  /var/run/docker.sock:/var/run/docker.sock
volumes:
  tomcat-data:
